// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKho.Models;

#nullable disable

namespace QuanLyKho.Migrations
{
    [DbContext(typeof(QuanLyKhoContext))]
    [Migration("20251206070450_HoanThienCacBangChiTiet")]
    partial class HoanThienCacBangChiTiet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKho.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaPN")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("MaPN");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaPX")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("MaPX");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("QuanLyKho.Models.DatHangNhap", b =>
                {
                    b.Property<string>("MaPhieuDat")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayNhapDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNgayCho")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhieuDat");

                    b.HasIndex("MaNCC");

                    b.ToTable("DatHangNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.Employee", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNV");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("QuanLyKho.Models.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaVon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KhachDat")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhoCha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("QuanLyKho.Models.KiemKeKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<string>("Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayKiemKe")
                        .HasColumnType("datetime2");

                    b.Property<int>("TonHeThong")
                        .HasColumnType("int");

                    b.Property<int>("TonThucTe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.ToTable("KiemKeKhos");
                });

            modelBuilder.Entity("QuanLyKho.Models.LichSuGiaoDich", b =>
                {
                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DoiTac")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaThamChieu")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGiaoDich");

                    b.ToTable("LichSuGiaoDich");
                });

            modelBuilder.Entity("QuanLyKho.Models.NCC", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("NoHienTai")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongMua")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhapHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.ToTable("NhapHangs");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaPhieuDat")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("date");

                    b.Property<string>("NhanVienMaNV")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TongGiaTri")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaPhieuDat")
                        .IsUnique()
                        .HasFilter("[MaPhieuDat] IS NOT NULL");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuat", b =>
                {
                    b.Property<string>("MaPX")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayXuat")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongGiaTri")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPX");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyKho.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhap")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QuanLyKho.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuat")
                        .HasForeignKey("MaPX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKho.Models.DatHangNhap", b =>
                {
                    b.HasOne("QuanLyKho.Models.NCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKho.Models.KiemKeKho", b =>
                {
                    b.HasOne("QuanLyKho.Models.HangHoa", "HangHoa")
                        .WithMany("KiemKeKhos")
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKho.Models.NhapHang", b =>
                {
                    b.HasOne("QuanLyKho.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKho.Models.NCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Models.DatHangNhap", "DatHang")
                        .WithOne("PhieuNhap")
                        .HasForeignKey("QuanLyKho.Models.PhieuNhap", "MaPhieuDat");

                    b.HasOne("QuanLyKho.Models.Employee", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNV");

                    b.Navigation("DatHang");

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKho.Models.NCC", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKho.Models.Employee", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKho.Models.DatHangNhap", b =>
                {
                    b.Navigation("PhieuNhap")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKho.Models.HangHoa", b =>
                {
                    b.Navigation("KiemKeKhos");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("QuanLyKho.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuat");
                });
#pragma warning restore 612, 618
        }
    }
}
